---
- hosts: localhost
  connection: local
  tasks:
    - name: Pull the latest code from the GitHub repository
      git:
        repo: 'https://github.com/paju3125/Flask-App.git'
        dest: /home/prajvalgandhi/deploy/Flask_App
        version: master

    - name: Create a virtual environment using venv
      command: python3 -m venv /home/prajvalgandhi/deploy/Flask_App/venv
      args:
        creates: /home/prajvalgandhi/deploy/Flask_App/venv/bin/activate

    - name: Install dependencies
      command: /home/prajvalgandhi/deploy/Flask_App/venv/bin/pip install -r /home/prajvalgandhi/deploy/Flask_App/requirements.txt

    - name: Start the Flask application
      command: nohup /home/prajvalgandhi/deploy/Flask_App/venv/bin/python /home/prajvalgandhi/deploy/Flask_App/app.py > /home/prajvalgandhi/deploy/Flask_App/app.log 2>&1 &
      args:
        chdir: /home/prajvalgandhi/deploy/Flask_App

