name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Application Repository
      uses: actions/checkout@v3
      with:
        repository: paju3125/Flask-App
        ref: master

    - name: Checkout Ansible Playbooks Repository
      uses: actions/checkout@v3
      with:
        repository: paju3125/ansible-playbook
        ref: main

    - name: Run Ansible Playbook
      run: |
        cd ansible-playbooks
        ansible-playbook -i localhost deploy.yml
