name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the application repository
    - name: Checkout Application Repository
      uses: actions/checkout@v3
      with:
        repository: paju3125/Flask-App
        ref: master

    # Check out the ansible-playbooks repository
    - name: Checkout Ansible Playbooks Repository
      uses: actions/checkout@v3
      with:
        repository: paju3125/ansible-playbook
        path: ansible-playbooks  # Specify a custom path if needed
        ref: main

    # List directories to verify the presence of the ansible-playbooks folder
    - name: List Directories
      run: ls -la

    - name: Check if Vault Password is Set
      id: check_vault
      run: |
        if [ -z "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" ]; then
          echo "Vault password not set"
          exit 1
        fi

    - name: Run Ansible Playbook
      if: steps.check_vault.outcome == 'success'
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      run: |
        echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass
        cd ansible-playbooks
        ansible-playbook -i localhost deploy.yml
