name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      target_key:
        description: "The version key to increment (APP_VERSION or TOOLS_VERSION)"
        required: true
        default: "APP_VERSION"
      version_part:
        description: "Which part to increment (major, minor, or patch)"
        required: true
        default: "patch"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the application repository
    - name: Checkout Application Repository
      uses: actions/checkout@v3
      with:
        repository: paju3125/Flask-App
        ref: master

    # Step 2: Increment the version
    - name: Increment Version
      run: |
        python scripts/increment_version.py .env "${{ github.event.inputs.target_key }}" "${{ github.event.inputs.version_part }}"

    # Step 3: Commit and push the updated .env file
    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/paju3125/Flask-App.git
        git add .env
        git commit -m "Incremented ${{ github.event.inputs.target_key }} (${{ github.event.inputs.version_part }})"
        git push origin ${{ github.ref_name }}